import type { MediaSourceStatus, StockMediaAsset } from "@/lib/types";

export const demoFallbackStatus: MediaSourceStatus = {
  adapter: "demo-fallback",
  label: "Read-only media index",
  detail: "Media export not found. These records are read-only fallback entries behind the server route contract.",
  readOnly: true
};

export const demoFallbackAssets: StockMediaAsset[] = [
  {
    id: "9101",
    title: "Bible Study Table",
    thumbnail: "",
    thumbnailAlt: "Bible on a study table",
    mediaType: "photo",
    collection: "Sabbath Service - Religious Education",
    status: "Approved Public",
    usageScope: "Public",
    peopleRisk: "No people",
    sourcePlatform: "Google Photos",
    sourceSystem: "LM Photos import",
    sourceAccount: "lm.photos@tjc.org",
    sourceAlbum: "Sabbath Service - Religious Education",
    sourceAlbumMemberships: ["Sabbath Service - Religious Education"],
    originalFilename: "LMPhotos_RE_Sabbath_BibleStudy_001.jpg",
    resourceSpaceId: "9101",
    imageDimensions: "2400 x 1600",
    rightsStatus: "TJC-owned",
    consentStatus: "not applicable",
    reviewer: "ResourceSpace admin",
    reviewedDate: "2026-06-04",
    rightsNotes: "Trusted lm.photos import fixture. Public-approved stock-safe default for discovery testing.",
    usageGuidance: "Approved for public ministry website, slides, and newsletter reuse.",
    downloadPolicy: "approved-copy-allowed",
    tags: ["Bible", "book", "classroom", "warm", "stock-safe"],
    tjcTerms: ["Sabbath Service", "Religious Education", "Bible study"],
    usageTerms: ["website", "slides", "newsletter", "stock-safe"],
    aiVisibleTagSuggestions: ["table", "open Bible", "study notes"],
    aiTjcTermSuggestions: ["Religious Education"],
    humanAiDecision: "edited"
  },
  {
    id: "9102",
    title: "Sabbath Flower Arrangement",
    thumbnail: "",
    thumbnailAlt: "Flower arrangement near church entry",
    mediaType: "photo",
    collection: "Sabbath Service Details",
    status: "Approved Public",
    usageScope: "Public",
    peopleRisk: "No people",
    sourcePlatform: "Google Photos",
    sourceSystem: "LM Photos import",
    sourceAccount: "lm.photos@tjc.org",
    sourceAlbum: "Sabbath Service Details",
    sourceAlbumMemberships: ["Sabbath Service Details"],
    originalFilename: "LMPhotos_Sabbath_Flowers_002.jpg",
    resourceSpaceId: "9102",
    imageDimensions: "2000 x 1600",
    rightsStatus: "TJC-owned",
    consentStatus: "not applicable",
    reviewer: "ResourceSpace admin",
    reviewedDate: "2026-06-04",
    rightsNotes: "Trusted lm.photos import fixture. No people visible.",
    usageGuidance: "Approved for public worship detail, newsletter, and slide background reuse.",
    downloadPolicy: "approved-copy-allowed",
    tags: ["flower", "plant", "seasonal", "warm", "stock-safe"],
    tjcTerms: ["Sabbath Service", "welcome"],
    usageTerms: ["website", "slides", "newsletter", "stock-safe"],
    aiVisibleTagSuggestions: ["floral arrangement", "church detail"],
    humanAiDecision: "accepted"
  },
  {
    id: "9103",
    title: "Fellowship Testimony Pending",
    thumbnail: "",
    thumbnailAlt: "Fellowship testimony context pending review",
    mediaType: "photo",
    collection: "Incoming Fellowship",
    status: "Needs Review",
    usageScope: "Do Not Publish",
    peopleRisk: "Adults visible",
    sourcePlatform: "Google Drive",
    sourceSystem: "Contributor upload",
    sourceAccount: "media.intake@tjc.org",
    sourceAlbum: "Incoming Fellowship",
    sourceAlbumMemberships: ["Incoming Fellowship"],
    originalFilename: "Contributor_Testimony_Fellowship_003.jpg",
    resourceSpaceId: "9103",
    rightsStatus: "needs review",
    consentStatus: "unknown",
    sensitiveContext: "testimony context-safe until reviewer confirms usage.",
    rightsNotes: "Needs reviewer approval before public use.",
    usageGuidance: "Context-safe candidate only; reviewer approval required before reuse.",
    downloadPolicy: "not-downloadable",
    tags: ["people", "table", "context-safe"],
    tjcTerms: ["Fellowship", "Testimony"],
    usageTerms: ["context-safe", "internal review"],
    aiVisibleTagSuggestions: ["people", "gathering"],
    aiTjcTermSuggestions: ["Testimony"],
    aiPeopleOrMinorFlag: "people visible",
    humanAiDecision: "not reviewed"
  },
  {
    id: "9104",
    title: "Choir Hymn Archive Audio",
    thumbnail: "",
    thumbnailAlt: "Archive-only hymn recording",
    mediaType: "audio",
    collection: "Hymns of Praise Archive",
    status: "Searchable Archive",
    usageScope: "Archive Only",
    peopleRisk: "Unknown",
    sourcePlatform: "Google Drive",
    sourceSystem: "Archive import",
    sourceAccount: "archive@tjc.org",
    sourceAlbum: "Hymns of Praise Archive",
    sourceAlbumMemberships: ["Hymns of Praise Archive"],
    originalFilename: "HymnsOfPraise_Archive_004.mp3",
    resourceSpaceId: "9104",
    rightsStatus: "hymn rights review required",
    consentStatus: "unknown",
    sensitiveContext: "music rights archive-only fixture.",
    rightsNotes: "Archive-only reference. Do not use for public publishing.",
    usageGuidance: "Archive-only; request music rights review before any channel reuse.",
    downloadPolicy: "not-downloadable",
    tags: ["choir", "audio", "archive-only"],
    tjcTerms: ["Hymns of Praise", "Sabbath Service"],
    usageTerms: ["archive only", "archive-only"],
    aiVisibleTagSuggestions: ["audio recording"],
    aiTjcTermSuggestions: ["Hymns of Praise"],
    aiPeopleOrMinorFlag: "unknown",
    humanAiDecision: "not reviewed"
  }
];
